import { processAllOrders } from '../src/dailyCalculatorUtils/calculator';
import { OrderItem, SettlementSettings } from '../src/dailyCalculatorTypes';

const settings: SettlementSettings = {
  defaultPackagingCost: 500,
  defaultActualShippingCost: 1900,
  defaultIncomeTaxRate: 10,
  vatCalculationMethod: 'simple10',
  autoBundleShipping: true,
  bundleOnlyFirstPackageCost: false,
  coupangDefaultFee: 13,
  coupangRiceFee: 6,
  homepageFee: 3.85,
  smartstoreBaseFee: 3.74,
  smartstoreKnowledgeFee: 2.0,
  ohouseDefaultFee: 16,
  elevenstDefaultFee: 13,
  gmarketDefaultFee: 13,
  auctionDefaultFee: 13,
};

const orders: OrderItem[] = [
  {
    id: 'ord-1',
    platform: 'smartstore',
    orderDate: '2026-08-18',
    orderNumber: '1001',
    productNumber: 'P1',
    productName: '조개 실리콘 냄비 손잡이 2P세트 - 민트',
    optionName: '기본',
    quantity: 1,
    recipient: '홍길동',
    recipientPhone: '',
    recipientAddress: '',
    unitPrice: 2000,
    totalPrice: 2000,
    buyerShippingFee: 0,
    isShippingFree: true,
    feeRate: 5.74,
    feeAmount: 100,
    knowledgeShoppingFee: 0,
    settlementAmount: 1900,
    unitCost: 800,
    totalCost: 800,
    packagingCost: 500,
    actualShippingCost: 1900,
    isBundleShipping: false,
    grossProfit: 0,
    vatDeductedProfit: 0,
    vatAmount: 0,
    incomeTax: 0,
    netProfit: 0,
    marginRate: 0,
    isCostMatched: true,
  },
  {
    id: 'ord-2',
    platform: 'smartstore',
    orderDate: '2026-08-18',
    orderNumber: '1002',
    productNumber: 'P2',
    productName: 'NHB 파스타쿠커 전자레인지 메이커',
    optionName: '기본',
    quantity: 1,
    recipient: '홍길동',
    recipientPhone: '',
    recipientAddress: '',
    unitPrice: 10000,
    totalPrice: 10000,
    buyerShippingFee: 0,
    isShippingFree: true,
    feeRate: 5.74,
    feeAmount: 500,
    knowledgeShoppingFee: 0,
    settlementAmount: 9500,
    unitCost: 3000,
    totalCost: 3000,
    packagingCost: 500,
    actualShippingCost: 1900,
    isBundleShipping: false,
    grossProfit: 0,
    vatDeductedProfit: 0,
    vatAmount: 0,
    incomeTax: 0,
    netProfit: 0,
    marginRate: 0,
    isCostMatched: true,
  },
];

const processed = processAllOrders(orders, [], settings);
console.log(processed.map(o => ({
  name: o.productName,
  recipient: o.recipient,
  buyerShippingFee: o.buyerShippingFee,
  actualShippingCost: o.actualShippingCost,
  isBundleShipping: o.isBundleShipping,
})));
